name: Hello World

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout our repository
      uses: actions/checkout@v4

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          pwd
          echo BOSHLANDIIIIIIIIIIIIIIIIIIIIIIIIIIi
          cd food
          git pull origin main

          cd Food-Delivery-Api-Gateway
          sudo docker compose down
          sudo docker compose up -d --build
          sudo docker compose down
          sudo docker compose up -d --build

          cd ..
          cd Food-Delivery-Auth-Service
          sudo docker compose down
          sudo docker compose up -d --build
          sudo docker compose down
          sudo docker compose up -d --build

          cd ..
          cd Food-Delivery-Delivery-Service
          sudo docker compose down
          sudo docker compose up -d --build

          sudo docker compose down
          sudo docker compose up -d --build
